[package]
name = "stiqr-print"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
firestore = "0.25.0"
iced = "0.7.0"
# reqwest = "0.11.14"
